name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination (gh-pages branch)
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Set up Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.112.4/hugo_extended_0.112.4_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      - name: Build the site
        run: ${RUNNER_TEMP}/hugo

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          # Copy the built site to the gh-pages branch directory
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          
          # Navigate to the gh-pages directory
          cd ${GITHUB_WORKSPACE}/built-site
          
          # Check if there are any changes in the directory
          git diff --exit-code || git commit -am 'Updated site'
          
          # Configure git user settings for commit
          git config user.name 'bahrani667'
          git config user.email 'bahrani667j@gmail.com'
          
          # Push changes to the gh-pages branch
          git push origin gh-pages
